[package]
name = "greenhorn-templating"
version = "0.1.0"
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
edition = "2018"

[dependencies]
greenhorn = {path = ".."}
scraper = "0.11.0"
async-std = "1.4.0"
ego-tree = "0.6.2"
