[package]
name = "greenhorn"
version = "0.1.0"
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-timer = "0.6.1"
futures = "0.3"
async-tungstenite = { git = "https://github.com/sdroege/async-tungstenite.git" }
log = "0.4.8"
tungstenite = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
serde_json = "1.0"

[dependencies.async-std]
version="1.0.1"

[dev-dependencies]
assert_matches = "1.3.0"
dummy_waker = { path = "dummy_waker" }
