[package]
name = "html_macro"
license = "MPL-2.0+"
version = "0.1.0"
authors = ["Raphael Bernhard <beraphae@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5.11"
quote = "1.0.2"
syn = "1.0"
proc-macro2 = "1.0"
