name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install cargo-ghp-upload
      run: cargo install --version 0.3.4 cargo-ghp-upload
    - name: Compile docs
      run: cargo doc --no-deps
    - name: Upload to GHP
      env:
        GH_TOKEN: ${{ secrets.GHP_TOKEN }}
      run: cargo ghp-upload -vv
